### ISSUE TITLE
Issues tab displays problems with node_modules READMEs

### ISSUE THREAD

**Issue by UsAndRufus** [Doctave/doctave#56]
# Problem
The desktop app is flagging almost 200 issues with our project. Most if not all are isseus with READMEs in the `node_modules` directory. Obviously, we don't own these and they are not included in the final build of the site.

Currently, the issues list is basically useless given the quantity of noise.

**Example**

<img width="266" alt="Screenshot 2023-09-12 at 15 57 36" src="https://github.com/Doctave/doctave/assets/4115329/d8ce1a8d-4c3f-4ea1-a4fc-9eafaff1324d">

# Proposed solution

Two ideas:

1. Add an `ignores` key to `doctave.yaml` that allows you to specify directories to ignore. This should come with `node_modules` already added
2. Ignore `node_modules` by default and don't allow any customisation

**Comment by begleynk** [comment]
Hi @UsAndRufus!

Would you be able to email me at nik@doctave.com about this issue? This repo is no longer related to the Doctave.com product. See #51 for details.

But in short, the current Doctave desktop app (not this repo's project) looks at all `.md` files that it finds. It uses the directory that contains the `doctave.yaml` file as the root of the project, and searches sub-folders recursively. `ignore` is one option, but I'd love to understand your project structure to give a better answer.

If you email me I'll get back to you with more details.

I'll close this ticket since it's not relevant to this repo any more.

**Comment by UsAndRufus** [comment]
Apologies, I tried to make sure they were the same project. Will email.
